version: '3'

networks:
  distribuidos:
    driver: bridge

services:
  app-invoice:
    build: ../app-invoice
    image: icesiops/appinvoice:0.1.0
    container_name: app-invoice
    ports:
      - "8006:8006"
    networks:
      - distribuidos
    restart: always
  app-pay:
    build: ../app-pay
    container_name: app-pay
    ports:
      - "8010:8010"
    networks:
      - distribuidos
    restart: always
  app-transaction:
    build: ../app-transaction
    container_name: app-transaction
    ports:
      - "8082:8082"
    networks:
      - distribuidos
    restart: always